version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml"
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            mkdir -p $CIRCLE_TEST_REPORTS/junit
            cp ~/junit/*.xml $CIRCLE_TEST_REPORTS/junit/
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit
