version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle clean

      - run: gradle assemble

      - run: gradle test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            ls ~/junit
            cp ~/junit/*.xml $CIRCLE_TEST_REPORTS/
            ls $CIRCLE_TEST_REPORTS
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit
